CREATE TABLE OFFICE_TABLE(
R_NUM NUMBER PRIMARY KEY,
R_NAME VARCHAR2(20) NOT NULL,
WINDOW_CNT NUMBER NOT NULL,
DOOR_CNT NUMBER NOT NULL,
FIRE NUMBER DEFAULT 0 NOT NULL,
WINDOW_SCE NUMBER DEFAULT 0 NOT NULL,
DOOR_SCE NUMBER DEFAULT 0 NOT NULL
);